export { AgentIX } from './AgentIX';
export { loadConfig } from './config';
export { ContractRegistry } from './contracts';
export { Database } from './database';
export { TransactionManager, type TxOptions } from './transaction';
export { WalletModule } from './wallet';
export { IdentityModule } from './identity';
export { SessionModule } from './session';
export { CredentialModule } from './credential';
export { OrganizationModule } from './organization';
export { CapabilityModule } from './capability';
export { DelegationModule } from './delegation';
export { EventIndexer } from './events';
export { OwnerModule } from './onlyOwner/index';

export type { Signer } from 'ethers';

export * from './types';

export {
  SignerRequiredError,
  NotOwnerError,
  NotEntryPointError,
  NotAuthorizedError,
  AlreadyInitializedError,
  NotInitializedError,
  InvalidOwnerError,
  ExecutionFailedError,
  CallFailedError,
  BatchTooLargeError,
  OwnershipTransferPendingError,
  InvalidOwnerSignatureError,
  BatchNotAllowedForSessionError,
  UnsupportedCallDataError,
  SessionNotFoundError,
  SessionExpiredError,
  SessionRevokedError,
  SessionAlreadyExistsError,
  NotWalletOwnerError,
  LimitExceededError,
  DailySpendLimitExceededError,
  DailyTxLimitExceededError,
  InvalidExpiryError,
  TooManySessionsError,
  InvalidProofError,
  NotAgentWalletError,
  InvalidImplementationError,
  WalletAlreadyExistsWithDifferentOwnerError,
  IdentityNotFoundError,
  IdentityInactiveError,
  IdentityAlreadyRegisteredError,
  NotIdentityOwnerError,
  InvalidMetadataRootError,
  MetadataRootUnchangedError,
  OnlyIssuerError,
  NullifierUsedError,
  RootCannotBeZeroError,
  OrganizationNotFoundError,
  OrganizationAlreadyExistsError,
  OrganizationInactiveError,
  CapabilityNotFoundError,
  CapabilityAlreadyExistsError,
  NotAuthorizedForCapabilityError,
  GrantNotRevocableError,
  DelegatorRevokedError,
  AlreadyRevokedDelegationError,
  IdentityAlreadyActiveError,
  InvalidIdentityIdError,
  NotFactoryError,
  ZeroAddressNotAllowedError,
  InvalidSessionManagerError,
  InvalidEntryPointError,
  LengthMismatchError,
  InvalidRecipientError,
  FundingFailedError,
  InvalidCallDataError,
  LightweightSessionValidationFailedError,
  SessionValidationFailedError,
  FactoryInvalidSessionManagerError,
  FactoryInvalidEntryPointError,
  FactoryInvalidOwnerError,
  FactoryTimelockNotReadyError,
  FactoryTimelockActiveError,
  InvalidAgentIdentityError,
  OnlySessionManagerError,
  ActionRequiredError,
  AlreadyRevokedCapabilityError,
  AlreadyRevokedGrantError,
  InvalidGrantRootError,
  EmptyChainError,
  ChainTooLongError,
  ArrayLengthMismatchError,
  ScopeAlreadyRegisteredError,
  ScopeLimitExceededError,
  InvalidOwnerAddressError,
  InvalidNameError,
  InvalidAnchorError,
  OrganizationAlreadyInactiveError,
  OrganizationAlreadyActiveError,
  AnchorTimelockNotReadyError,
  AnchorTimelockActiveError,
  InvalidOrganizationIdError,
  RootAlreadyCurrentError,
  UnauthorizedUpdateError,
  RevokedRootCannotBeZeroError,
  InvalidSessionKeyError,
  NullifierMismatchError,
  RootMismatchError,
  RevokedRootMismatchError,
  MaxValueMismatchError,
  ExpiryMismatchError,
  InvalidSignerError,
  SessionAlreadyRevokedError,
  NotAuthorizedToRevokeError,
  NotBoundWalletError,
  UnsupportedCredentialVersionError,
  WalletFactoryTimelockNotReadyError,
  WalletFactoryTimelockActiveError,
  InvalidNullifierError,
  TargetNotAllowedError,
  TooManyTargetsError,
  TimelockNotReadyError,
  TimelockActiveError,
  ConfigurationError,
  RpcError,
  ValidationError,
  mapContractError,
} from './errors';

export * from './utils';
